name: export_save
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  minio: ^3.5.7
  rxdart: ^0.28.0
  injectable: ^2.4.4
  get_it: ^7.7.0
  provider: ^6.1.5+1
  dartz: ^0.10.1
  sqflite_common: ^2.5.5
  sqflite_common_ffi: ^2.3.6
  qr_flutter: ^4.1.0
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
